### ISSUE TITLE
The attachment of Black Box is empty.

### ISSUE THREAD

**Issue by tr4v3ler** [chaitin/Real-World-CTF-4th-Challenge-Attachments#2]
Where can I get the attachment of Black Box?

**Comment by tr4v3ler** [comment]
The attachments of other topics are also incomplete. Can you provide complete attachments?

**Comment by zh-explorer** [comment]
Because this repo is only for the `attachments`, not the `environment`. The "Black Box" and some other challenges do not have attachments because they are black box challenges or web pentest.
So if you want a challenging environment for replay. Tell me so I can ask the author of the challenge for some help.

**Comment by tr4v3ler** [comment]
> Because this repo is only for the `attachments`, not the `environment`. The "Black Box" and some other challenges do not have attachments because they are black box challenges or web pentest. So if you want a challenging environment for replay. Tell me so I can ask the author of the challenge for some help.

Thanks for your reply, if there is no attachment in the black box environment, then don't bother you.
